//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.3

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "order")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub user: String,
    pub filler: String,
    pub source_chain_selector: String,
    pub destination_chain_selector: String,
    pub sponsored: bool,
    pub primary_filler_deadline: DateTime,
    pub deadline: DateTime,
    pub call_recipient: Option<String>,
    pub call_data: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
