//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.3

use sea_orm::entity::prelude::*;

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "order_status")]
pub enum OrderStatus {
    #[sea_orm(string_value = "Created")]
    Created,
    #[sea_orm(string_value = "Filled")]
    Filled,
    #[sea_orm(string_value = "Withdrawn")]
    Withdrawn,
}
